# This is a basic workflow to help you get started with Actions

name: Build Site

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ code ]

jobs:
  build:
    name: shalzz/zola-deploy-action
    runs-on: ubuntu-latest
    steps:
    # Checkout
    - uses: actions/checkout@master
    # Build & deploy
    - name: shalzz/zola-deploy-action
      uses: shalzz/zola-deploy-action@v0.12.0
      env:
        # Target branch
        PAGES_BRANCH: master
        # Provide personal access token
        TOKEN: ${{ secrets.TOKEN }}