[[badges]]
  link = "https://ptnote.dev"
  image = "/images/ptnote.png"
  alt = "ptnote.dev"
[[badges]]
  link = "https://archiveofourown.org"
  image = "/images/ao3.gif"
  alt = "AO3"
[[badges]]
  link = "https://www.gnu.org/software/emacs/"
  image = "/images/emacsnow.gif"
  alt = "emacs now!"
[[badges]]
  link = "https://www.mozilla.org/en-US/firefox/"
  image = "/images/getfirefox.gif"
  alt = "Get Firefox"
[[badges]]
  link = "https://www.web3isgoinggreat.com/"
  image = "/images/web3.gif"
  alt = "Say No to Web3"
[[badges]]
  link = "https://thesatanictemple.com/"
  image = "/images/get-eucharist.gif"
  alt = "Get the Eucharist!"
[[badges]]
  link = "https://giantitp.com/comics/oots.html"
  image = "/images/oots.gif"
  alt = "The Order of the Stick"
[[badges]]
  link = "https://www.hypnospace.net/"
  image = "/images/beefbrain.gif"
  alt = "This Brain Protected by BeefBrain Shield Pro"
[[badges]]
  link = "/humans.txt"
  image = "/images/human.png"
  alt = "Written By a Human"
[[badges]]
  link = "https://neocities.org/"
  image = "/images/website.gif"
  alt = "Start a Website"
[[badges]]
  link = "https://wiki.lspace.org/Main_Page/"
  image = "/images/lspace.gif"
  alt = "LSpace Now!"
[[badges]]
  link = "https://archive.org/"
  image = "/images/archive.gif"
  alt = "The Internet Archive"
[[badges]]
  link = "https://glaad.org/"
  image = "/images/homosexuality.gif"
  alt = "Homosexuality Now!"
[[badges]]
  link = "https://alula.github.io/SpaceCadetPinball/"
  image = "/images/98plus.gif"
  alt = "98 Plus!"
[[badges]]
  link = "https://www.effinbirds.com/collections/nfts"
  image = "/images/antinft.gif"
  alt = "This is an Anti-NFT site"
[[badges]]
  link = "https://eightyeightthirty.one"
  image = "/images/8831.png"
  alt = "eightyeightthirty.one"
[[badges]]
  link = "https://hayl.in"
  image = "/images/haylin.webp"
  alt = "Haylin"
[[badges]]
  link = "https://rust-lang.org"
  image = "/images/runrust.webp"
  alt = "Run Rust"
[[badges]]
  link = "https://tokipona.org"
  image = "/images/tokipona.gif"
  alt = "toki pona tenpo ni a"
[[badges]]
  link = "https://umass.edu"
  image = "/images/umass.webp"
  alt = "UMass Amherst"
[[badges]]
  link = "https://jordane.day"
  image = "/images/jordan.gif"
  alt = "Jordan"
[[badges]]
  link = "https://nostalgicforthe.net"
  image = "/images/swillion.gif"
  alt = "Swillion"
